---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 14일 무료 평가판이 종료된 후 동기화 관계에 대한 비용을 지불할 수 있는 두 가지 방법이 있습니다. 첫 번째 옵션은 사용한 만큼만 지불하는 것입니다. 두 번째 옵션은 NetApp에서 직접 라이센스를 구매하는 것입니다. 
---
= 무료 평가판이 끝난 후 동기화 관계에 대한 비용을 지불합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
14일 무료 평가판이 종료된 후 동기화 관계에 대한 비용을 지불할 수 있는 두 가지 방법이 있습니다. 첫 번째 옵션은 AWS 또는 Azure에서 용량제 또는 연간 결제를 구독하는 것입니다. 두 번째 옵션은 NetApp에서 직접 라이센스를 구매하는 것입니다.

AWS Marketplace 또는 Azure Marketplace에서 구독할 수 있습니다. 두 경우 모두 구독할 수 없습니다.

Marketplace 구독에서 NetApp의 라이센스를 사용할 수 있습니다. 예를 들어, 동기화 관계가 25개 있는 경우 라이센스를 사용하여 처음 20개 동기화 관계에 대한 비용을 지불하고 나머지 5개 동기화 관계를 사용하여 AWS 또는 Azure에서 사용한 만큼만 비용을 지불할 수 있습니다.

link:concept-licensing.html["라이센스 작동 방식에 대해 자세히 알아보십시오"].

무료 평가판이 종료된 후 즉시 지불하지 않으면 추가 관계를 만들 수 없습니다. 기존 관계는 삭제되지 않지만 라이선스를 구독하거나 입력할 때까지 관계를 변경할 수 없습니다.

라이센스는 BlueXP 복사 및 동기화 또는 해당 웹 사이트를 통해 관리해야 하며 * 디지털 지갑을 통해 관리할 수 없습니다.



== [[AWS]] AWS에서 구독

AWS를 사용하면 사용한 만큼만 지불하거나 연간 단위로 비용을 지불할 수 있습니다.

.선불 종량제 단계
. BlueXP  탐색 메뉴에서 * 이동성 > 복사 및 동기화 * 를 선택합니다.
. 라이센스 * 를 선택합니다.
. AWS * 를 선택합니다.
. Subscribe * 를 선택한 다음 * Continue * 를 선택합니다.
. AWS Marketplace에서 구독한 다음 BlueXP 복사 및 동기화 서비스에 다시 로그인하여 등록을 완료합니다.
+
다음 비디오는 프로세스를 보여 줍니다.

+
.BlueXP  복사본을 구독하고 AWS Marketplace에서 동기화합니다
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.연간 지불 절차
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS 마켓플레이스 페이지로 이동합니다"^].
. Continue to Subscribe * 를 선택합니다.
. 계약 옵션을 선택한 다음 * 계약 작성 * 을 선택합니다.




== [[Azure]] Azure에서 구독

Azure를 사용하면 사용한 만큼만 지불하거나 연간 단위로 비용을 지불할 수 있습니다.

.필요한 것
관련 구독에 참가자 또는 소유자 권한이 있는 Azure 사용자 계정입니다.

.단계
. BlueXP  탐색 메뉴에서 * 이동성 > 복사 및 동기화 * 를 선택합니다.
. 라이센스 * 를 선택합니다.
. Azure * 를 선택합니다.
. Subscribe * 를 선택한 다음 * Continue * 를 선택합니다.
. Azure 포털에서 * Create * 를 선택하고 옵션을 선택한 다음 * Subscribe * 를 선택합니다.
+
월간 * 을 선택하여 시간당 결제하거나, * Yearly * 를 선택하여 1년 단위로 선불로 결제합니다.

. 배포가 완료되면 알림 팝업에서 SaaS 리소스의 이름을 선택합니다.
. BlueXP 복사 및 동기화로 돌아가려면 * 계정 구성 * 을 선택합니다.
+
다음 비디오는 프로세스를 보여 줍니다.

+
.BlueXP  복사본을 구독하고 Azure 마켓플레이스에서 동기화합니다
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[licenses]] NetApp에서 라이센스를 구입하고 BlueXP  복사본 및 동기화에 추가합니다

동기화 관계를 사전에 결제하려면 하나 이상의 라이센스를 구입하여 BlueXP 복사 및 동기화 서비스에 추가해야 합니다.

.필요한 것
라이센스에 대한 일련 번호 및 라이센스가 연결된 NetApp Support 사이트 계정의 사용자 이름과 암호가 필요합니다.

.단계
. 라이센스를 mailto:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[NetApp 문의]까지 구입하십시오.
. BlueXP  탐색 메뉴에서 * 이동성 > 복사 및 동기화 * 를 선택합니다.
. 라이센스 * 를 선택합니다.
. Add License * 를 선택하고 필요한 정보를 추가합니다.
+
.. 일련 번호를 입력합니다.
.. 추가하는 라이센스와 연관된 NetApp Support 사이트 계정을 선택합니다.
+
*** 계정이 이미 BlueXP에 추가된 경우 드롭다운 목록에서 선택합니다.
*** 계정이 아직 추가되지 않은 경우 * NSS 자격 증명 추가 * 를 선택하고 사용자 이름 및 암호를 입력한 다음 * 등록 * 을 선택하고 드롭다운 목록에서 선택합니다.


.. 추가 * 를 선택합니다.






== 라이센스를 업데이트합니다

NetApp에서 구매한 BlueXP 사본 및 동기화 라이센스를 연장한 경우, BlueXP 사본 및 동기화에서 새 만료일이 자동으로 업데이트되지 않습니다. 만료 날짜를 새로 고치려면 라이센스를 다시 추가해야 합니다. 라이센스는 BlueXP 복사 및 동기화 또는 해당 웹 사이트를 통해 관리해야 하며 * 디지털 지갑을 통해 관리할 수 없습니다.

.단계
. BlueXP  탐색 메뉴에서 * 이동성 > 복사 및 동기화 * 를 선택합니다.
. 라이센스 * 를 선택합니다.
. Add License * 를 선택하고 필요한 정보를 추가합니다.
+
.. 일련 번호를 입력합니다.
.. 추가하고 있는 라이센스와 관련된 NetApp Support 사이트 계정을 선택합니다.
.. 추가 * 를 선택합니다.




.결과
BlueXP 복사 및 동기화는 기존 라이센스를 새 만료일로 업데이트합니다.
